all: clean v2

clean:
	rm -rf convolution

v2: clean
	mpicc convolution_v2.c  -I/home/shishido/opencv/install/include/opencv -I/home/shishido/opencv/install/include -L/home/shishido/opencv/install/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib -lopencv_legacy -Iutil -o convolution
